triggers:
  branches:
    include:
      - main

pr: 
  branches:
    include:
      - main
pool:
  name: macbook-selfhosted
  
variables:
  buildConfiguration: 'Release'

job:
  name: 'HookRelay Pipeline'

#Setup .NET 9 sdk
steps:
  
#Restore nugget packages
  
#build the solution 
  
  